stages:
  - test

test:
  image: "python:3.9-buster"
  stage: test
  interruptible: true
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - python --version
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
  script:
    - ./test.sh
  coverage: '/TOTAL.*\s+(\d+%)$/'
